### PR TITLE
Fix #132 by respecting indent_size from .editorconfig

### LINKED ISSUE #132: Configuring indent_size from .editorconfig broken
No longer honors the value specified, although configuring it in the `kotlinter` extension still works.

This functionality appears to have broken between 2.0.0 and 2.1.0, so somewhere in #111 things went wrong. Needs investigation. Could have been the ktlint upgrade or changes to this plugin.

### PR DESCRIPTION
**Pull request by mateuszkwiecinski**
Fixes #132 

The reson why properties set in `.editorconfig` weren't respected is that we were always passing them in ktlint's userData which are higher in hierarchy than those set in `.editorconfig`.

In addition I removed support for `continuation_indent_size` as it is no longer recognized by ktlint https://github.com/pinterest/ktlint/issues/171 (I could mark it as deprecated though 🤔WDYT?)

### CODE REVIEW

File: src/main/kotlin/org/jmailen/gradle/kotlinter/KotlinterExtension.kt [hunk 1]
```diff
@@ -16,9 +14,7 @@ open class KotlinterExtension {
     /** Don't fail build on lint issues */
     var ignoreFailures = DEFAULT_IGNORE_FAILURES
 
-    var indentSize = DEFAULT_INDENT_SIZE
-
-    var continuationIndentSize = DEFAULT_CONTINUATION_INDENT_SIZE
```
[the remark this answers is not in the document]
Comment (jeremymailen) [reply src/main/kotlin/org/jmailen/gradle/kotlinter/KotlinterExtension.kt]: If you wish to remove it from the readme, you can or I'll make those updates when I push the version bump.

File: src/test/kotlin/org/jmailen/gradle/kotlinter/functional/EditorConfigTest.kt [hunk 2]
```diff
@@ -0,0 +1,93 @@
...
+                }
+                
+            """.trimIndent()
+                writeText(buildScript)
+            }
+        }
+    }
+
+    @Test
+    fun `lintTask uses default indentation if editorconfig absent`() {
```
Comment (jeremymailen) [inline src/test/kotlin/org/jmailen/gradle/kotlinter/functional/EditorConfigTest.kt]: oh good, so that's ktlint default when there isn't userData or an .editorconfig.

File: src/test/kotlin/org/jmailen/gradle/kotlinter/functional/EditorConfigTest.kt [hunk 3]
```diff
@@ -0,0 +1,93 @@
...
+            )
+        }
+
+        build("lintKotlin").apply {
+            assertEquals(TaskOutcome.SUCCESS, task(":lintKotlinMain")?.outcome)
+        }
+    }
+
+    @Test
+    fun `plugin respects indentSize set in editorconfig`() {
```
Comment (jeremymailen) [inline src/test/kotlin/org/jmailen/gradle/kotlinter/functional/EditorConfigTest.kt]: What about the test case that when both kotlinter.indentSize is specified and there's an .editorconfig with the param, the extension wins? Based on the code I expect this to work of course.

File: src/main/kotlin/org/jmailen/gradle/kotlinter/KotlinterExtension.kt (hunk 1 above)
[the remark this answers is not in the document]
Comment (mateuszkwiecinski) [reply src/main/kotlin/org/jmailen/gradle/kotlinter/KotlinterExtension.kt]: Done ✅ 
Added deprecation messages, both for tasks and for the extension. Removed all `continuationIndentSize` mentions from Readme.

File: src/test/kotlin/org/jmailen/gradle/kotlinter/functional/EditorConfigTest.kt (hunk 3 above)
Comment (mateuszkwiecinski) [reply src/test/kotlin/org/jmailen/gradle/kotlinter/functional/EditorConfigTest.kt]: Done ✅ Added precedence checks for both `disabledRules` and `indentSize`
